// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scnqcjmxewwdnwijiiym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjbnFjam14ZXd3ZG53aWppaXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzUyMjksImV4cCI6MjA2NjMxMTIyOX0.Ui18Dp35ypR3rQUeOn65xano68DEQysGCTjQt5Dhh0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);